<?php
/**
 * @file
 * Election primary module file.
 */

// Required files.
require_once 'includes/election.constants.inc';

/**
 * Implements hook_entity_info().
 */
function election_entity_info() {

  $entities = array();

  $entities['election'] = array(
    'label' => t('Election'),
    'access callback' => 'election_access',
    'uri callback' => 'election_uri',
    'controller class' => 'ElectionController',
    'base table' => 'election',
    'entity keys' => array(
      'id' => 'election_id',
      'label' => 'title',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'static cache' => TRUE,
    'fieldable' => TRUE,
    'module' => 'election',
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => TRUE,
      ),
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => TRUE,
      ),
    ),
  );

  $entities['election_post'] = array(
    'label' => t('Election post'),
    'access callback' => 'election_post_access',
    'uri callback' => 'election_post_uri',
    'controller class' => 'ElectionPostController',
    'base table' => 'election_post',
    'entity keys' => array(
      'id' => 'post_id',
      'label' => 'title',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'static cache' => TRUE,
    'fieldable' => TRUE,
    'module' => 'election',
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => TRUE,
      ),
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => TRUE,
      ),
    ),
    'redirect' => FALSE, // for the Redirect module
  );

  foreach (election_types() as $type_mn => $type) {
    $entities['election']['bundles'][$type_mn] = array(
      'label' => drupal_ucfirst($type['name']),
      'admin' => array(
        'path' => 'admin/election/' . $type_mn,
        'real path' => 'admin/election/' . $type_mn,
        'bundle argument' => 2,
        'access arguments' => array('administer elections'),
      ),
    );
    if (!empty($type['post key'])) {
      $post_key = $type['post key'];
      $post_name = _election_get_posts_name($type_mn);
      $entities['election_post']['bundles'][$post_key] = array(
        'label' => drupal_ucfirst($post_name),
        'admin' => array(
          'path' => 'admin/election/' . $type_mn . '/' . $post_key,
          'real path' => 'admin/election/' . $type_mn . '/' . $post_key,
          'bundle argument' => 3,
          'access arguments' => array('administer elections'),
        ),
      );
    }
  }

  $entities['election_candidate'] = array(
    'label' => t('Election candidate'),
    'access callback' => 'election_candidate_access',
    'uri callback' => 'election_candidate_uri',
    'controller class' => 'ElectionCandidateController',
    'base table' => 'election_candidate',
    'label callback' => 'election_candidate_label',
    'entity keys' => array(
      'id' => 'candidate_id',
    ),
    'static cache' => TRUE,
    'fieldable' => TRUE,
    'module' => 'election',
    'bundles' => array(
      // Single bundles are named after the entity type (see entity_extract_ids()).
      'election_candidate' => array(
        'label' => t('Election candidate'),
        'admin' => array(
          'path' => 'admin/election/candidate',
          'access arguments' => array('administer elections'),
        ),
      ),
    ),
    'view modes' => array(
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => TRUE,
      ),
    ),
    'redirect' => FALSE, // for the Redirect module
  );

  return $entities;

}

/**
 * Return information about election types in a structured array, keyed by
 * each type's machine name. Each element is also a structured array defining at
 * least 'name' and 'post key'.
 *
 * This uses hook_election_type_info() to allow other modules to define types.
 *
 * @return array
 */
function election_types() {
  $types = &drupal_static(__FUNCTION__);
  if (empty($types)) {
    $types = array();
    $types['referendum'] = array(
      'name' => t('referendum'),
      'description' => t('A simple referendum, where people can vote once (yes, no, or abstain) in response to a motion.'),
      'post name' => t('motion'),
      'post name plural' => t('motions'),
      'post key' => 'motion',
      'weight' => 0,
    );
    $types['stv'] = array(
      'name' => t('STV election'),
      'description' => t('A Single Transferable Vote election, conforming to the Electoral Reform Society\'s ERS97 standard.'),
      'post name' => t('position'),
      'post name plural' => t('positions'),
      'post key' => 'position',
      'weight' => 1,
    );
    $types += module_invoke_all('election_type_info');
  }
  return $types;
}

/*
 * Return an array of election type names, keyed by machine name.
 *
 * @param bool $ucfirst
 *   Whether to apply drupal_ucfirst() to each election type name.
 *
 * @return array
 */
function election_type_get_names($ucfirst = TRUE) {
  $names = array();
  $types = election_types();
  foreach ($types as $mn => $type) {
    $names[$mn] = $ucfirst? drupal_ucfirst($type['name']) : $type['name'];
  }
  return $names;
}

/**
 * Implements hook_views_api().
 */
function election_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'election') . '/views',
  );
}

/**
 * Implements entity_uri(). URI callback for a single election. See:
 * http://api.drupal.org/api/drupal/includes--common.inc/function/entity_uri/7.
 *
 * @return array
 */
function election_uri($election) {
  $path = 'election/' . $election->election_id;
  return array(
    'path' => $path,
  );
}

/*
 * Return the path part of the election URI callback as a string.
 *
 * The implementation of this function throughout the module is debatable, see:
 * http://drupal.org/node/823428.
 *
 * @see election_uri()
 *
 * @return string
 */
function election_uri_path($election) {
  $uri = entity_uri('election', $election);
  return $uri['path'];
}

/**
 * URI callback for a single election post.
 *
 * @return array
 */
function election_post_uri($post) {
  $path = 'election-posts/' . $post->post_id;
  if (!empty($post->election_id)) {
    $election = election_load($post->election_id);
    $path = election_uri_path($election) . '/posts/' . $post->post_id;
  }
  return array(
    'path' => $path,
  );
}

/**
 * Return the path part of the election post URI callback as a string.
 *
 * @return string.
 */
function election_post_uri_path($post) {
  $uri = entity_uri('election_post', $post);
  return $uri['path'];
}

/**
 * URI callback for a single election candidate.
 *
 * @return array
 */
function election_candidate_uri($candidate) {
  $path = 'election-candidate/' . $candidate->candidate_id;
  if (!empty($candidate->election_id)) {
    $election = election_load($candidate->election_id);
    $path = election_uri_path($election) . '/candidate/' . $candidate->candidate_id;
  }
  return array(
    'path' => $path,
  );
}

/**
 * Return the path part of the election candidate URI callback as a string.
 *
 * @return string.
 */
function election_candidate_uri_path($candidate) {
  $uri = entity_uri('election_candidate', $candidate);
  return $uri['path'];
}

/**
 * Label callback for an election_candidate, returning the candidate's name.
 *
 * @param stdClass $entity
 * @param string $entity_type
 *
 * @return string
 */
function election_candidate_label(stdClass $entity, $entity_type) {
  return $entity->first_name . ' ' . $entity->last_name;
}

/**
 * Load an individual election.
 *
 * @param mixed $election_id
 *   A single election ID.
 *
 * @return stdClass
 *   A stdClass election object.
 */
function election_load($election_id = NULL) {
  $result = entity_load('election', (array) $election_id);
  if (!is_array($result) || !count($result)) {
    return FALSE;
  }
  return reset($result);
}

/**
 * Return information about all electorates.
 *
 * @todo document this
 *
 * @return array
 */
function election_electorates() {
  $result = db_query('SELECT * FROM {election_electorate} ORDER BY name');

  $electorates = array();

  $code_electorates = _election_get_code_electorates();

  while ($electorate = $result->fetchAssoc()) {
    $key = $electorate['machine_name'];
    if ($electorate['locked']) {
      if (isset($code_electorates[$key])) {
        $electorate['conditions'] = (array) @$code_electorates[$key]['conditions'];
      }
    }
    else {
      $electorate['conditions'] = (array) unserialize($electorate['conditions']);
    }
    $key = $electorate['machine_name'];
    $electorates[$key] = $electorate;
  }

  return $electorates;
}

/**
 * Return information about code electorates in a structured array, keyed by each
 * electorate's machine name. Each element is also a structured array defining at
 * least 'name' and 'access callback'. The key 'access callback' refers to a
 * function that takes one argument (the Drupal $user object) and returns
 * whether or not the user is part of the electorate (as a Boolean value).
 *
 * This function uses hook_electorate_info() to allow other modules to
 * define electorates.
 *
 * @return array
 */
function _election_get_code_electorates() {
  $electorates = &drupal_static(__FUNCTION__);
  if (empty($electorates)) {
    $electorates = array();
    $electorates += module_invoke_all('electorate_info');
  }
  return $electorates;
}

/**
 * Implements hook_modules_enabled().
 */
function election_modules_enabled($modules = array()) {
  /*
    If any of the enabled modules contains an implementation of
    hook_electorate_info, run _election_install_code_electorates().
  */
  foreach ($modules as $module) {
    if (function_exists($module . '_electorate_info')) {
      _election_install_code_electorates();
      break;
    }
  }
}

/**
 * Implements hook_modules_disabled().
 */
function election_modules_disabled($modules = array()) {
  /*
    If any of the disabled modules contains an implementation of
    hook_electorate_info, run _election_uninstall_code_electorates().
  */
  foreach ($modules as $module) {
    if (function_exists($module . '_electorate_info')) {
      _election_uninstall_code_electorates();
      break;
    }
  }
}

/*
 * Delete electorates from the DB only if they are not assigned to any posts AND
 * they do not (or no longer) exist in code.
 *
 * @return void
 */
function _election_uninstall_code_electorates() {
  $code_electorates = _election_get_code_electorates();
  $transaction = db_transaction();
  try {
    $db_electorates = db_query('SELECT electorate_id, machine_name FROM {election_electorate} WHERE locked = 1');
    while ($db_electorate = $db_electorates->fetchAssoc()) {
      // Don't delete electorates that (still) exist in code.
      if (isset($code_electorates[$db_electorate['machine_name']])) {
        continue;
      }
      // Don't delete assigned electorates.
      // @todo with a bit of thought this could be run as a JOIN on the $db_electorates query above.
      $assigned = db_query_range(
        'SELECT 1 FROM {election_post_electorate} WHERE electorate_id = :eid',
        0, 1,
        array(':eid' => $db_electorate['electorate_id'])
      );
      if ($assigned->rowCount()) {
        continue;
      }
      db_delete('election_electorate')
        ->condition('electorate_id', $db_electorate['electorate_id'])
        ->execute();
      watchdog(
        'election',
        'Deleted the electorate %machine_name from the database as it is no longer in use.',
        array('%machine_name' => $db_electorate['machine_name'])
      );
    }
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception(
      'election',
      $e,
      'Failed to remove from the database those electorates that no longer exist in code.',
      WATCHDOG_ERROR
    );
    return FALSE;
  }
}

/**
 * Find electorates in code and write them (identified by 'machine name') to the
 * {election_electorate} table. This uses a Merge Query, see:
 * http://drupal.org/node/310085
 * and:
 * http://api.drupal.org/api/drupal/includes--database--query.inc/class/MergeQuery/7
 *
 * @return void
 */
function _election_install_code_electorates() {
  foreach (_election_get_code_electorates() as $electorate_mn => $electorate) {
    $record = array(
      'machine_name' => $electorate_mn,
      'name' => empty($electorate['name'])? $electorate_mn : $electorate['name'],
      'description' => @$electorate['description'],
      'locked' => 1,
      'changed' => REQUEST_TIME,
    );
    db_merge('election_electorate')
      ->key(array('machine_name' => $electorate_mn))
      ->updateFields($record)
      ->insertFields($record + array('created' => REQUEST_TIME))
      ->execute();
  }
}


/**
 * Load multiple elections.
 *
 * @param mixed $election_id
 *   An array of election IDs.
 *
 * @return stdClass
 *   A stdClass election object.
 */
function election_load_multiple(array $election_ids = array()) {
  return entity_load('election', $election_ids);
}

/**
 * Load an individual election post.
 *
 * @param mixed $post_id
 *   A single election post ID.
 *
 * @return stdClass
 *   A stdClass post object.
 */
function election_post_load($post_id = NULL) {
  $result = entity_load('election_post', (array) $post_id);
  if (!is_array($result) || !count($result)) {
    return FALSE;
  }
  return reset($result);
}

/**
 * Load multiple posts.
 *
 * @param mixed $post_ids
 *   An array of post IDs.
 *
 * @return stdClass
 *   A stdClass election_post object.
 */
function election_post_load_multiple(array $post_ids = array()) {
  return entity_load('election_post', $post_ids);
}

/**
 * Load an individual election candidate.
 *
 * @param mixed $candidate_id
 *   A single election candidate ID.
 *
 * @return stdClass
 *   A stdClass election_candidate object.
 */
function election_candidate_load($candidate_id = NULL) {
  $result = entity_load('election_candidate', (array) $candidate_id);
  if (!is_array($result) || !count($result)) {
    return FALSE;
  }
  return reset($result);
}

/**
 * Load multiple candidates.
 *
 * @param mixed $candidate_ids
 *   An array of election candidate IDs.
 *
 * @return stdClass
 *   A stdClass election_candidate object.
 */
function election_candidate_load_multiple(array $candidate_ids = array()) {
  return entity_load('election_candidate', $candidate_ids);
}


/**
 * Implements hook_permission().
 *
 * @return array
 */
function election_permission() {
  $permissions = array(
    'administer elections' => array(
      'title' => t('Administer elections'),
      'description' => t('Alter the fields and display settings for election types.'),
    ),
    'vote in elections' => array(
      'title' => t('Vote in elections'),
      'description' => t('Users must have this permission in order to vote. They must also belong to the relevant electorate(s).'),
    ),
    'create elections' => array(
      'title' => t('Create elections'),
    ),
    'delete any elections' => array(
      'title' => t('Delete any election'),
      'description' => t('This permission is dangerous: deleting an election automatically deletes ALL associated data, for example votes.'),
      'restrict access' => TRUE,
    ),
    'edit any election' => array(
      'title' => t('Edit any election'),
      'description' => t('This permission allows the user not only to edit elections, but also to administer the posts and candidates for those elections.'),
    ),
    'view any election' => array(
      'title' => t('View any election'),
      'description' => t('This permission allows the user to view elections, including those elections\' posts and approved candidates.'),
    ),
    'bypass nomination schedule' => array(
      'title' => t('Bypass nomination schedule'),
      'description' => t('This allows the user to submit a nomination at any time, regardless of whether or not nominations are open.'),
    ),
    'bypass nomination exclusivity' => array(
      'title' => t('Bypass nomination exclusivity'),
      'description' => t('This allows the user to submit a nomination for more than one exclusive position.'),
    ),
    'allow duplicate nominations' => array(
      'title' => t('Allow duplicate nominations'),
      'description' => t('This allows the user to submit more than one nomination for the same position.'),
    ),
    'submit nominations' => array(
      'title' => t('Submit nominations'),
      'description' => t('This allows the user to submit a nomination, only when nominations are open.'),
    ),
    'edit own nominations' => array(
      'title' => t('Edit own nominations'),
      'description' => t('This allows the user to edit his/her own nominations.'),
    ),
  );
  return $permissions;
}

/**
 * Determines whether the given user has access to an election.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $election
 *   Optionally an election or an election type to check access for. If nothing is
 *   given, access for all elections is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function election_access($op, $election = NULL, $account = NULL) {
  switch ($op) {
    case 'view':
      return (bool) user_access('view any election', $account);
      break;
    case 'create':
      return (bool) user_access('create elections', $account);
      break;
    case 'update':
    case 'edit':
      return (bool) user_access('edit any election', $account);
      break;
    case 'nomination':
      if (empty($election) || $election->type == 'referendum') {
        return FALSE;
      }
      return (bool) user_access('submit nominations', $account);
      break;
    case 'edit candidates':
      if (empty($election) || $election->type == 'referendum') {
        // candidates are n/a
        return FALSE;
      }
      return (bool) election_candidate_access('edit', NULL, $account);
      break;
    case 'delete':
      return (bool) user_access('delete any election', $account);
      break;
  }
  return FALSE;
}

/**
 * Determines whether the given user has access to a given election candidate.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $candidate
 *   Optionally a candidate to check access for. If nothing is
 *   given, access for all candidates is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function election_candidate_access($op, $candidate = NULL, $account = NULL) {
  if ($account === NULL) {
    global $user;
    $account = $user;
  }
  switch ($op) {
    case 'view':
      if (user_access('edit any election', $account)) {
        return TRUE;
      }
      if ($candidate && $candidate->cstatus == ELECTION_CANDIDATE_APPROVED && user_access('view any election', $account)) {
        return TRUE;
      }
      break;
    case 'edit':
    case 'update':
    case 'delete':
    case 'view details':
      if (user_access('edit any election', $account)) {
        return TRUE;
      }
      break;
    case 'create':
      // Creating must happen through the nomination form, not via entity_access.
      return FALSE;
      break;
  }
  if ($candidate === NULL || empty($candidate->uid) || $candidate->uid !== $account->uid) {
    // This is not the account's nomination, and global checks have failed.
    return FALSE;
  }
  // This is the $acccount's nomination.
  switch ($op) {
    case 'view':
    case 'view details':
      return TRUE;
      break;
    case 'edit':
    case 'update':
      return (bool) user_access('edit own nominations', $account);
      break;
    default:
      return FALSE;
      break;
  }
}

/**
 * Implements hook_menu().
 */
function election_menu() {

  $items = array();

  $items['admin/election'] = array(
    'title' => 'Elections',
    'description' => 'Administer elections and referendums.',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer elections'),
    'weight' => 1,
  );

  $items['admin/election/list'] = array(
    'title' => 'Election list',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_list_form'),
    'access arguments' => array('administer elections'),
    'file' => 'election.admin.inc',
    'description' => 'View, edit, and add new elections.',
    'weight' => -10,
  );

  foreach (election_types() as $type_mn => $type) {
    $items['admin/election/list/add/' . $type_mn] = array(
      'title' => 'Add new ' . $type['name'],
      'title callback' => 'check_plain',
      'page callback' => 'election_page_add',
      'page arguments' => array(4),
      'access arguments' => array('administer elections'),
      'file' => 'election.admin.inc',
      'description' => empty($type['description'])? '' : $type['description'],
      'type' => MENU_LOCAL_ACTION,
      'weight' => isset($type['weight'])? $type['weight'] : 0,
    );
    $items['admin/election/' . $type_mn] = array(
      'title' => drupal_ucfirst($type['name']) . ' settings',
      'title callback' => 'check_plain',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('administer elections'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
      'description' => empty($type['description'])? '' : $type['description'],
      'weight' => isset($type['weight'])? $type['weight'] : 0,
    );
    if (!empty($type['post key'])) {
      $post_key = $type['post key'];
      $post_name = _election_get_posts_name($type_mn);
      $post_name_plural = _election_get_posts_name($type_mn, TRUE);
      $items['admin/election/' . $type_mn . '/' . $post_key] = array(
        'title' => drupal_ucfirst($post_name) . ' settings',
        'title callback' => 'check_plain',
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer elections'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
        'description' => 'Manage fields and display settings for ' . $post_name_plural . '.',
      );
    }
  }

  $items['admin/election/candidate'] = array(
    'title' => 'Candidate settings',
    'description' => 'Manage fields and display settings for election candidates (not applicable to referendums).',
    'title callback' => 'check_plain',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer elections'),
  );
  $items['admin/election/candidate/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['elections'] = array(
    'title' => 'Elections',
    'page callback' => 'views_page', // @todo make this views_embed_view or a wrapper
    'page arguments' => array('elections', 'default'),
    'access callback' => 'election_access',
    'access arguments' => array('view'),
    'file path' => drupal_get_path('module', 'views'),
    'file' => 'views.module',
  );

  $items['election/%election'] = array(
    'title callback' => 'election_page_title',
    'title arguments' => array(1),
    'page callback' => 'election_page_view',
    'page arguments' => array(1),
    'access callback' => 'election_access',
    'access arguments' => array('view', 1),
    'file' => 'election.pages.inc',
  );

  $items['election/%election/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['election/%election/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'election_page_edit',
    'file' => 'election.admin.inc',
    'page arguments' => array(1),
    'access callback' => 'election_access',
    'access arguments' => array('update', 1),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['election/%election/nomination-form'] = array(
    'title' => 'Nomination form',
    'page callback' => 'election_page_nomination_form',
    'page arguments' => array(1),
    'access callback' => 'election_access',
    'access arguments' => array('nomination', 1),
    'file' => 'election-candidate.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => 2,
  );

  $items['election/%election/posts'] = array(
    'title callback' => 'election_page_postlist_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_post_list_form', 1),
    'file' => 'election-post.admin.inc',
    'access callback' => 'election_access',
    'access arguments' => array('update', 2),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['election/%election/candidates'] = array(
    'title' => 'Candidates',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_candidate_list_form', 1),
    'access callback' => 'election_access',
    'access arguments' => array('edit candidates', 1),
    'file' => 'election-candidate.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['election/%election/candidates/list'] = array(
    'title' => 'List candidates',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['election/%election/candidates/totals'] = array(
    'title' => 'View totals',
    'page callback' => 'election_candidate_totals_page',
    'page arguments' => array(1),
    'access callback' => 'election_access',
    'access arguments' => array('edit candidates', 1),
    'file' => 'election-candidate.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['election/%election/candidates/download'] = array(
    'title' => 'Download data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_candidate_download_form', 1),
    'access callback' => 'election_access',
    'access arguments' => array('edit candidates', 1),
    'file' => 'election-candidate.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['election/%election/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_form_delete_confirm', 1),
    'access callback' => 'election_access',
    'access arguments' => array('delete', 1),
    'file' => 'election.admin.inc',
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );

  $items['election/%election/candidate/%election_candidate'] = array(
    'title callback' => 'election_candidate_page_title',
    'title arguments' => array(1, 3),
    'page callback' => 'election_candidate_page_view',
    'page arguments' => array(1, 3),
    'file' => 'election-candidate.pages.inc',
    'access callback' => 'election_candidate_access',
    'access arguments' => array('view', 3),
    'type' => MENU_CALLBACK,
  );

  $items['election/%election/candidate/%election_candidate/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['election/%election/candidate/%election_candidate/details'] = array(
    'title' => 'Details',
    'page callback' => 'election_candidate_details_page_view',
    'page arguments' => array(1, 3),
    'file' => 'election-candidate.pages.inc',
    'access callback' => 'election_candidate_access',
    'access arguments' => array('view details', 3),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => 1,
  );

  $items['election/%election/candidate/%election_candidate/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_candidate_edit_form', 1, 3),
    'file' => 'election-candidate.pages.inc',
    'access callback' => 'election_candidate_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => 2,
  );

  $items['election/%election/candidate/%election_candidate/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_candidate_edit_form_delete_confirm', 1, 3),
    'access callback' => 'election_candidate_access',
    'access arguments' => array('delete', 3),
    'file' => 'election-candidate.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );

  $items['election/%election/posts/add'] = array(
    'title' => 'Add new',
    'page callback' => 'election_post_page_add',
    'page arguments' => array(1),
    'access callback' => 'election_access',
    'access arguments' => array('update', 1),
    'file' => 'election-post.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['election/%election/posts/%election_post'] = array(
    'title callback' => 'election_post_page_title',
    'title arguments' => array(1, 3),
    'page callback' => 'election_post_page_view',
    'page arguments' => array(1, 3),
    'file' => 'election.pages.inc',
    'access callback' => 'election_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
  );

  $items['election/%election/posts/%election_post/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['election/%election/posts/%election_post/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'election_post_page_edit',
    'page arguments' => array(1, 3),
    'file' => 'election-post.admin.inc',
    'access callback' => 'election_access',
    'access arguments' => array('update', 1),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => 1,
  );

  $items['election/%election/posts/%election_post/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('election_post_form_delete_confirm', 1, 3),
    'access callback' => 'election_access',
    'access arguments' => array('update', 1),
    'file' => 'election-post.admin.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );

  return $items;

}

/**
 * Implements hook_menu_alter().
 */
function election_menu_alter(&$items) {
  return;
  foreach (election_types() as $type_mn => $type) {
    $path = 'admin/election/' . $type_mn;
    unset($items[$path . '/settings']);
    $items[$path . '/fields']['weight'] = -2;
    $items[$path . '/fields']['type'] = MENU_NORMAL_ITEM;
    $items[$path . '/fields']['description'] = t(
      'Manage fields for the election type %type.',
      array('%type' => $type['name'])
    );
    $items[$path . '/display']['weight'] = -1;
    $items[$path . '/display']['type'] = MENU_NORMAL_ITEM;
    $items[$path . '/display/full']['type'] = MENU_NORMAL_ITEM;
    $items[$path . '/display/teaser']['type'] = MENU_NORMAL_ITEM;
    $items[$path . '/display']['description'] = t(
      'Manage display for the election type %type.',
      array('%type' => $type['name'])
    );
    if (!empty($type['post key'])) {
      $post_key = $type['post key'];
      $post_name_plural = _election_get_posts_name($type_mn, TRUE);
      $items[$path . '/' . $post_key]['type'] = MENU_NORMAL_ITEM;
      $items[$path . '/' . $post_key . '/fields']['type'] = MENU_NORMAL_ITEM;
      $items[$path . '/' . $post_key . '/fields']['description'] = t(
        'Manage fields for %type @posts_name_plural.',
        array(
          '%type' => $type['name'],
          '@posts_name_plural' => $post_name_plural,
        )
      );
      $items[$path . '/' . $post_key . '/display']['type'] = MENU_NORMAL_ITEM;
      $items[$path . '/' . $post_key . '/display/full']['type'] = MENU_NORMAL_ITEM;
      $items[$path . '/' . $post_key . '/display/teaser']['type'] = MENU_NORMAL_ITEM;
      $items[$path . '/' . $post_key . '/display']['description'] = t(
        'Manage display for %type @posts_name_plural.',
        array(
          '%type' => $type['name'],
          '@posts_name_plural' => $post_name_plural,
        )
      );
    }
  }
  unset($items['admin/election/candidate/settings']);
  $items['admin/election/candidate/fields']['type'] = MENU_NORMAL_ITEM;
  $items['admin/election/candidate/fields']['description'] = t('Manage fields for election candidates.');
  $items['admin/election/candidate/display']['type'] = MENU_NORMAL_ITEM;
  $items['admin/election/candidate/display']['description'] = t('Manage display for election candidates.');
}

/*
 * Implements hook_field_extra_fields().
 *
 * @return array
 */
function election_field_extra_fields() {
  $extra = array();
  $extra['election']['referendum'] = array(
    'form' => array(
      'title' => array(
        'label' => t('Title'),
        'description' => t('The referendum title.'),
        'weight' => 0,
      ),
      'vstatus' => array(
        'label' => t('Voting status'),
        'weight' => 1,
      ),
      'vschedule' => array(
        'label' => t('Voting schedule'),
        'weight' => 2,
      ),
      'anonymous' => array(
        'label' => t('Voter anonymity'),
        'description' => t('The anonymity settings for this referendum.'),
        'weight' => 3,
      ),
    ),
  );
  $extra['election']['stv'] = array(
    'form' => array(
      'title' => array(
        'label' => t('Title'),
        'description' => t('The election title.'),
        'weight' => 0,
      ),
      'nstatus' => array(
        'label' => t('Nominations status'),
        'weight' => 1,
      ),
      'nschedule' => array(
        'label' => t('Nominations schedule'),
        'weight' => 2,
      ),
      'vstatus' => array(
        'label' => t('Voting status'),
        'weight' => 3,
      ),
      'vschedule' => array(
        'label' => t('Voting schedule'),
        'weight' => 4,
      ),
      'anonymous' => array(
        'label' => t('Voter anonymity'),
        'description' => t('The anonymity settings for this election.'),
        'weight' => 5,
      ),
    ),
  );
  $extra['election_candidate']['election_candidate'] = array(
    'form' => array(
      'post' => array(
        'label' => t('Post'),
        'description' => t('The post for this nomination.'),
        'weight' => -1,
      ),
      'first_name' => array(
        'label' => t('First name'),
        'description' => t('The candidate\'s first name(s).'),
        'weight' => 0,
      ),
      'last_name' => array(
        'label' => t('Last name'),
        'description' => t('The candidate\'s last name(s).'),
        'weight' => 1,
      ),
      'mail' => array(
        'label' => t('Email address'),
        'description' => t('The candidate\'s email address.'),
        'weight' => 2,
      ),
      'phone' => array(
        'label' => t('Phone number'),
        'description' => t('The candidate\'s phone number.'),
        'weight' => 3,
      ),
    ),
    'display' => array(
      'election' => array(
        'label' => t('Election'),
        'description' => t('The election for this nomination.'),
        'weight' => 0,
      ),
      'post' => array(
        'label' => t('Post'),
        'description' => t('The post/position for this nomination.'),
        'weight' => 1,
      ),
      'full-name' => array(
        'label' => t('Name'),
        'description' => t('The candidate\'s name.'),
        'weight' => 2,
      ),
    ),
  );
  return $extra;
}

/**
 * Wrapper function to allow deleting multiple elections.
 *
 * @param array $election_ids
 *   Array of election IDs.
 * @return bool
 */
function election_delete_multiple(array $election_ids) {
  return entity_get_controller('election')->delete($election_ids);
}

/**
 * Wrapper function to allow deleting an individual election.
 *
 * @see election_delete_multiple()
 *
 * @param mixed $election_id
 *   Single election ID.
 * @return bool
 */
function election_delete($election_id) {
  return election_delete_multiple(array($election_id));
}

/**
 * Wrapper function to allow saving an election.
 *
 * @param stdClass $election
 *   Election object.
 * @return bool
 */
function election_save($election) {
  return entity_get_controller('election')->save($election);
}

/**
 * Implements hook_entity_update().
 */
function election_entity_update($entity, $type) {
  switch ($type) {
    case 'election':
      if (function_exists('pathauto_election_update_alias')) {
        pathauto_election_update_alias($entity, 'update');
      }
    break;
  }
}

/**
 * Implements hook_entity_delete().
 */
function election_entity_delete($entity, $type) {
  switch ($type) {
    case 'election':
      if (function_exists('pathauto_entity_path_delete_all')) {
        pathauto_entity_path_delete_all('election', $entity);
      }
    break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function election_entity_insert($entity, $type) {
  switch ($type) {
    case 'election':
      if (function_exists('pathauto_election_update_alias')) {
        pathauto_election_update_alias($entity, 'insert');
      }
    break;
    case 'election_post':
      $transaction = db_transaction();
      try {
        db_delete('election_post_electorate')
          ->condition('post_id', $entity->post_id)
          ->execute();
        foreach ($entity->electorates as $electorate_id) {
          db_insert('election_post_electorate')->fields(array(
            'post_id' => $entity->post_id,
            'electorate_id' => $electorate_id,
          ))->execute();
        }
        _election_uninstall_code_electorates();
      }
      catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('election', $e, NULL, WATCHDOG_ERROR);
        return FALSE;
      }
      return TRUE;
    break;
  }
}

/**
 * Wrapper function to allow deleting multiple election posts.
 *
 * @param array $post_ids
 *   Array of post IDs.
 * @return bool
 */
function election_post_delete_multiple(array $post_ids) {
  return entity_get_controller('election_post')->delete($post_ids);
}

/**
 * Wrapper function to allow deleting an individual election post.
 *
 * @see election_post_delete_multiple()
 *
 * @param mixed $post_id
 *   Single post ID.
 * @return bool
 */
function election_post_delete($post_id) {
  return election_post_delete_multiple(array($post_id));
}

/**
 * Wrapper function to allow saving an election post.
 *
 * @param stdClass $post
 *   Election post object.
 * @return bool
 */
function election_post_save($post) {
  return entity_get_controller('election_post')->save($post);
}

/**
 * Title callback for election/%election/posts (output should not
 * be escaped here as it is done later).
 *
 * @param stdClass $election
 *
 * @return string
 */
function election_page_postlist_title($election) {
  return drupal_ucfirst(_election_get_posts_name($election->type, TRUE));
}

/**
 * Title callback for election/%election/posts/%election_post (output should not
 * be escaped here as it is done later).
 *
 * @param stdClass $election
 * @param stdClass $post
 *
 * @return string
 */
function election_post_page_title($election, $post) {
  return $post->title;
}

/**
 * Title callback for election/%election/view (output should not be escaped here
 * as it is done later).
 *
 * @param stdClass $election
 *
 * @return string
 */
function election_page_title($election) {
  return $election->title;
}

/**
 * Title callback for election/%election_candidate/view (output should not be escaped here
 * as it is done later).
 *
 * @param stdClass $election
 * @param stdClass $candidate
 *
 * @return string
 */
function election_candidate_page_title($election, $candidate) {
  return $candidate->first_name . ' ' . $candidate->last_name;
}

/**
 * Wrapper function to allow saving an election candidate.
 *
 * @param stdClass $candidate
 *   Election candidate object.
 * @return bool
 */
function election_candidate_save($candidate) {
  return entity_get_controller('election_candidate')->save($candidate);
}

/**
 * Wrapper function to allow deleting multiple candidates.
 *
 * @param array $candidate_ids
 *   Array of candidate IDs.
 * @return bool
 */
function election_candidate_delete_multiple(array $candidate_ids) {
  return entity_get_controller('election_candidate')->delete($candidate_ids);
}

/**
 * Wrapper function to allow deleting an individual election.
 *
 * @see election_candidate_delete_multiple()
 *
 * @param mixed $candidate_id
 *   Single candidate ID.
 * @return bool
 */
function election_candidate_delete($candidate_id) {
  return election_candidate_delete_multiple(array($candidate_id));
}


/*
 * Find the nominations (election_candidate entities) for a specified election
 * and user.
 *
 * @param stdClass $election
 *   Election object.
 * @param stdClass $account
 *   Optional $user object.
 *
 * @return
 *   FALSE if the account is anonymous, or a SelectQuery object.
 */
function election_candidate_get_user_nominations(stdClass $election, $account = NULL) {
  if ($account === NULL) {
    global $user;
    $account = $user;
  }
  if ($account->uid == 0) {
    return array();
  }
  $select = db_query(
    'SELECT ec.*, ep.title AS post_title, ep.exclusive FROM {election_candidate} ec LEFT JOIN {election_post} ep USING (post_id) WHERE ec.uid = :uid AND ep.election_id = :eid',
    array(
      ':eid' => $election->election_id,
      ':uid' => $account->uid,
    )
  );
  return $select->fetchAll();
}

/*
 * Find the posts that a candidate may be nominated for.
 *
 * @param stdClass $election
 *   Election object.
 * @param array $nominations
 *   Array of the user's previous nominations (election_candidate objects).
 * @param stdClass $account
 *   User object.
 *
 * @return
 *   Array of post IDs.
 */
function election_candidate_get_available_posts(stdClass $election, $nominations = NULL, $account = NULL) {
  if ($nominations === NULL) {
    if ($account === NULL) {
      global $user;
      $account = $user;
    }
    $nominations = election_candidate_get_user_nominations($election, $account);
  }
  $has_exclusive = FALSE;
  $prev_post_ids = array();
  foreach ($nominations as $nomination) {
    if ($nomination->exclusive) {
      $has_exclusive = TRUE;
    }
    $prev_post_ids[] = $nomination->post_id;
  }
  $select = db_select('election_post', 'ep')->fields('ep', array('post_id'));
  $select->condition('election_id', $election->election_id, '=');
  if ($prev_post_ids && !user_access('allow duplicate nominations')) {
    $select->condition('post_id', $prev_post_ids, 'NOT IN');
  }
  if ($has_exclusive && !user_access('bypass nomination exclusivity')) {
    $select->condition('exclusive', 0, '=');
  }
  $select->orderBy('title');
  $result = $select->execute();
  return $result->fetchCol();
}

/**
 * Implements hook_token_info().
 * See http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_token_info/7.
 */
function election_token_info() {
  $info = array();
  $info['types'] = array(
    'election' => array(
      'name' => t('Elections'),
      'description' => t('Tokens related to elections.'),
      'needs-data' => 'election',
    ),
    'election_candidate' => array(
      'name' => t('Candidates'),
      'description' => t('Tokens related to election candidates.'),
      'needs-data' => 'election_candidate',
    ),
  );
  $info['tokens'] = array(
    'election' => array(
      'id' => array(
        'name' => t('Election ID'),
        'description' => t('The unique ID of the election.'),
      ),
      'type' => array(
        'name' => t('Election type'),
        'description' => t('The machine-readable name of the election type.'),
      ),
      'type_name' => array(
        'name' => t('Election type name'),
        'description' => t('The human-readable name of the election type.'),
      ),
      'title' => array(
        'name' => t('Title'),
        'description' => t('The title of the election.'),
      ),
      'created' => array(
        'name' => t('Date created'),
        'description' => t('The date the election was created.'),
        'type' => 'date',
      ),
    ),
    'election_candidate' => array(
      'id' => array(
        'name' => t('Election candidate ID'),
        'description' => t('The unique ID of the candidate.'),
      ),
      'mail' => array(
        'name' => t('Email address'),
        'description' => t('The email address of the candidate.'),
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function election_tokens($type, array $tokens, array $data = array(), array $options = array()) {
  $sanitize = !empty($options['sanitize']);
  $replacements = array();
  if ($type == 'election' && !empty($data['election'])) {
    $election = $data['election'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'id':
          $replacements[$original] = $election->election_id;
          break;
        case 'type':
          $replacements[$original] = $sanitize ? check_plain($election->type) : $election->type;
          break;
        case 'type_name':
          $type = _election_type_get_info($election->type);
          $type_name = $type['name'];
          $replacements[$original] = $sanitize ? check_plain($type_name) : $type_name;
          break;
        case 'title':
          $replacements[$original] = $sanitize ? check_plain($election->title) : $election->title;
          break;
        case 'created':
          $replacements[$original] = format_date($election->created, 'medium');
          break;
      }
    }
  }
  else if ($type == 'election_candidate' && !empty($data['election_candidate'])) {
    $candidate = $data['election_candidate'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'id':
          $replacements[$original] = $candidate->candidate_id;
          break;
        case 'mail':
          $replacements[$original] = $sanitize ? check_plain($candidate->mail) : $candidate->mail;
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_pathauto(). See the Pathauto module.
 *
 * @param string $op
 * @return stdClass
 */
function election_pathauto($op) {
  switch ($op) {
    case 'settings':
      $settings = array();
      $settings['module'] = 'election';
      $settings['token_type'] = 'election';
      $settings['groupheader'] = t('Election paths');
      $settings['patterndescr'] = t('Default path pattern (applies to all election types with blank patterns below)');
      $settings['patterndefault'] = 'election/[election:title]';
      $settings['batch_update_callback'] = 'election_pathauto_bulk_update_batch_process';
      $settings['batch_file'] = drupal_get_path('module', 'election') . '/election.module';
      foreach (election_types() as $type_mn => $type) {
        $settings['patternitems'][$type_mn] = t('Pattern for all %type paths', array('%type' => $type['name']));
      }
      return (object) $settings;
    default:
      break;
  }
}

/**
 * Allow bulk updating of paths. See the Pathauto module.
 *
 * @see election_pathauto()
 * @param array &$context
 * @return void
 */
function election_pathauto_bulk_update_batch_process(&$context) {
  if (!isset($context['sandbox']['current'])) {
    $context['sandbox']['count'] = 0;
    $context['sandbox']['current'] = 0;
  }
  $query = db_select('election', 'e');
  $query->leftJoin('url_alias', 'ua', "CONCAT('election/', e.election_id) = ua.source");
  $query->addField('e', 'election_id');
  $query->isNull('ua.source');
  $query->condition('e.election_id', $context['sandbox']['current'], '>');
  $query->orderBy('e.election_id');
  $query->addTag('pathauto_bulk_update');
  $query->addMetaData('entity', 'election');
  // Get the total amount of items to process.
  if (!isset($context['sandbox']['total'])) {
    $context['sandbox']['total'] = $query->countQuery()->execute()->fetchField();
    // If there are no elections to update, then stop immediately.
    if (!$context['sandbox']['total']) {
      $context['finished'] = 1;
      return;
    }
  }
  $query->range(0, 25);
  $ids = $query->execute()->fetchCol();
  pathauto_election_update_alias_multiple($ids, 'bulkupdate');
  $context['sandbox']['count'] += count($ids);
  $context['sandbox']['current'] = max($ids);
  $context['message'] = t('Updated alias for election @id.', array('@id' => end($ids)));
  if ($context['sandbox']['count'] != $context['sandbox']['total']) {
    $context['finished'] = $context['sandbox']['count'] / $context['sandbox']['total'];
  }
}

/**
 * Update the URL aliases for an individual election.
 *
 * @param $election
 *   A election object.
 * @param $op
 *   Operation being performed on the election ('insert', 'update' or 'bulkupdate').
 * @param $options
 *   An optional array of additional options.
 */
function pathauto_election_update_alias(stdClass $election, $op, array $options = array()) {
  // Skip processing if the user has disabled pathauto for the election.
  if (isset($election->path['pathauto']) && empty($election->path['pathauto'])) {
    return;
  }
  $options += array(
    'language' => isset($election->language) ? $election->language : LANGUAGE_NONE,
  );
  // Skip processing if the election has no pattern.
  if (!pathauto_pattern_load_by_entity('election', $election->type, $options['language'])) {
    return;
  }
  module_load_include('inc', 'pathauto');
  pathauto_create_alias(
    'election',
    $op,
    election_uri_path($election),
    array('election' => $election),
    $election->type,
    $options['language']
  );
}

/**
 * Update the URL aliases for multiple elections.
 *
 * @param $election_ids
 *   An array of election IDs.
 * @param $op
 *   Operation being performed on the elections ('insert', 'update' or
 *   'bulkupdate').
 * @param $options
 *   An optional array of additional options.
 */
function pathauto_election_update_alias_multiple(array $election_ids, $op, array $options = array()) {
  $options += array('message' => FALSE);
  $elections = election_load_multiple($election_ids);
  foreach ($elections as $election) {
    pathauto_election_update_alias($election, $op, $options);
  }
  if (!empty($options['message'])) {
    drupal_set_message(format_plural(count($election_ids), 'Updated URL alias for 1 election.', 'Updated URL aliases for @count elections.'));
  }
}

/**
 * Implements hook_path_alias_types(). See Pathauto module.
 *
 * Used primarily by the bulk delete form.
 */
function election_path_alias_types() {
  $objects = array(
    'election/' => t('Elections')
  );
  return $objects;
}

/**
 * Implements hook_theme().
 */
function election_theme() {
  return array(
    'election' => array(
      'render element' => 'elements',
      'template' => 'election',
    ),
    'election_post' => array(
      'render element' => 'elements',
      'template' => 'election-post',
    ),
    'election_candidate' => array(
      'render element' => 'elements',
      'template' => 'election-candidate',
    ),
    'election_candidate_details' => array(
      'render element' => 'elements',
      'template' => 'election-candidate-details',
    ),
  );
}

/**
 * Generate an array for rendering the given election.
 *
 * @param $election
 *   An election object.
 * @param $view_mode
 *   View mode, e.g. 'full', 'teaser'...
 *
 * @return
 *   An array as expected by drupal_render().
 */
function election_view($election, $view_mode = 'full') {

  // Remove previously built content, if it exists.
  $election->content = array();

  if ($view_mode == 'teaser') {
    $election->content['title'] = array(
      '#markup' => filter_xss($election->title),
      '#weight' => -5,
    );
  }
  else {
    drupal_set_title($election->title);
  }

  // Build fields content.
  // In case of a multiple view, node_view_multiple() already ran the
  // 'prepare_view' step. An internal flag prevents the operation from running
  // twice.
  field_attach_prepare_view('election', array($election->election_id => $election), $view_mode);
  entity_prepare_view('election', array($election->election_id => $election));
  $election->content += field_attach_view('election', $election, $view_mode);

  $build = $election->content;
  // We don't need duplicate rendering info in election->content.
  unset($election->content);

  $build += array(
    '#theme' => 'election',
    '#election' => $election,
    '#view_mode' => $view_mode,
  );

  // Add contextual links for this election, except when the election is already being
  // displayed on its own page. Modules may alter this behavior (for example,
  // to restrict contextual links to certain view modes) by implementing
  // hook_election_view_alter().
  if (!empty($election->election_id) && $view_mode != 'full') {
    $build['#contextual_links']['election'] = array('election', array($election->election_id));
  }

  // Allow modules to modify the structured election.
  $type = 'election'; // $type is passed by reference to drupal_alter() so it must be a variable.
  drupal_alter(array('election_view', 'entity_view'), $build, $type);

  return $build;

}

/**
 * Process variables for election.tpl.php
 *
 * The $variables array contains the following arguments:
 * - $election
 * - $view_mode
 * - $page
 *
 * @see election.tpl.php
 */
function template_preprocess_election(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Provide a distinct $teaser boolean.
  $variables['teaser'] = $variables['view_mode'] == 'teaser';
  $variables['election'] = $variables['elements']['#election'];
  $election = $variables['election'];

  $uri = entity_uri('election', $election);
  $variables['election_url'] = url($uri['path'], $uri['options']);
  $variables['title']     = check_plain($election->title);
  $variables['page']      = $variables['view_mode'] == 'full';

  $variables['vstatus'] = _election_format_status($election, 'v');
  $variables['nstatus'] = _election_format_status($election, 'n');

  // Flatten the election object's member fields.
  $variables = array_merge((array) $election, $variables);

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Make the field variables available with the appropriate language.
  field_attach_preprocess('election', $election, $variables['content'], $variables);

  $variables['classes_array'][] = drupal_html_class('election-type-' . $election->type);

  $variables['theme_hook_suggestions'][] = 'election__' . $election->type;
  $variables['theme_hook_suggestions'][] = 'election__' . $election->election_id;

}

/**
 * Generate an array for rendering the given election post.
 *
 * @param $election
 *   An election object.
 * @param $view_mode
 *   View mode, e.g. 'full', 'teaser'...
 *
 * @return
 *   An array as expected by drupal_render().
 */
function election_post_view($election, $post, $view_mode = 'full') {

  // Remove previously built content, if it exists.
  $post->content = array();

  if ($view_mode == 'teaser') {
    $post->content['title'] = array(
      '#markup' => filter_xss($post->title),
      '#weight' => -5,
    );
  }
  else {
    drupal_set_title($post->title);
  }

  // Build fields content.
  // In case of a multiple view, node_view_multiple() already ran the
  // 'prepare_view' step. An internal flag prevents the operation from running
  // twice.
  field_attach_prepare_view('election_post', array($post->post_id => $post), $view_mode);
  entity_prepare_view('election_post', array($post->post_id => $post));
  $post->content += field_attach_view('election_post', $post, $view_mode);

  $build = $post->content;
  // We don't need duplicate rendering info in post->content.
  unset($post->content);

  $build += array(
    '#theme' => 'election_post',
    '#election' => $election,
    '#post' => $post,
    '#view_mode' => $view_mode,
  );

  // Add contextual links for this post, except when the post is already being
  // displayed on its own page. Modules may alter this behavior (for example,
  // to restrict contextual links to certain view modes) by implementing
  // hook_post_view_alter().
  if (!empty($post->post_id) && $view_mode != 'full') {
    $build['#contextual_links']['election_post'] = array('election_post', array($post->post_id));
  }

  // Allow modules to modify the structured post.
  $type = 'election_post'; // $type is passed by reference to drupal_alter() so it must be a variable.
  drupal_alter(array('post_view', 'entity_view'), $build, $type);

  return $build;

}

/**
 * Process variables for election-post.tpl.php
 *
 * The $variables array contains the following arguments:
 * - $election
 * - $view_mode
 * - $page
 *
 * @see election-post.tpl.php
 */
function template_preprocess_election_post(&$variables) {

  $variables['view_mode'] = $variables['elements']['#view_mode'];

  // Provide a distinct $teaser boolean.
  $variables['teaser'] = $variables['view_mode'] == 'teaser';

  $variables['election'] = $variables['elements']['#election'];
  $election = $variables['election'];

  $variables['post'] = $variables['elements']['#post'];
  $post = $variables['post'];

  $uri = entity_uri('election_post', $post);
  $variables['election_post_url'] = url($uri['path'], $uri['options']);
  $variables['title'] = check_plain($post->title);
  $variables['page'] = $variables['view_mode'] == 'full';
  $variables['exclusivity'] = $post->exclusive? t('This is an exclusive position.') : t('This is not an exclusive position.');
  $variables['exclusivity_help'] = t('Candidates may only stand for one exclusive position per election.');

  // Flatten the election object's member fields.
  $variables = array_merge((array) $post, $variables);

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Make the field variables available with the appropriate language.
  field_attach_preprocess('election', $election, $variables['content'], $variables);

  // Gather classes.
  $variables['classes_array'][] = drupal_html_class('election-post-' . $election->type);

  // Clean up name so there are no underscores.
  $variables['theme_hook_suggestions'][] = 'election_post__' . $election->type;
  $variables['theme_hook_suggestions'][] = 'election_post__' . $election->election_id;

}

/**
 * Process variables for election-candidate.tpl.php
 *
 * The $variables array contains the following arguments:
 * - $candidate
 * - $election
 * - $view_mode
 * - $page
 *
 * @see election-candidate.tpl.php
 */
function template_preprocess_election_candidate(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  // $teaser boolean
  $variables['teaser'] = $variables['view_mode'] == 'teaser';
  // $details boolean
  $variables['details'] = $variables['view_mode'] == 'details';
  // $page boolean
  $variables['page'] = ($variables['view_mode'] == 'full' || $variables['view_mode'] == 'details');

  $variables['election'] = $variables['elements']['#election'];
  $variables['candidate'] = $variables['elements']['#candidate'];
  $variables['post'] = $variables['elements']['#post'];

  $election = $variables['election'];
  $candidate = $variables['candidate'];
  $post = $variables['post'];
  $election_type = _election_type_get_info($election->type);

  if (empty($post)) {
    // Handle gracefully when the candidate's post is deleted prematurely.
    $post = entity_get_controller('election_post')->create(array(
      'type' => $election_type['post key'],
    ));
  }

  $uri = entity_uri('election_candidate', $candidate, $election);
  $variables['url'] = url($uri['path'], $uri['options']);

  $election_uri = entity_uri('election', $election);
  $variables['election_url'] = url($election_uri['path'], $election_uri['options']);
  $variables['election_title'] = check_plain($election->title);
  $variables['election_link'] = l($election->title, $election_uri['path'], $election_uri['options']);
  $variables['election_type'] = check_plain($election_type['name']);

  $post_uri = entity_uri('election_post', $post);
  $variables['post_url'] = url($post_uri['path'], $post_uri['options']);
  $variables['post_title'] = check_plain($post->title);
  $variables['post_link'] = l($post->title, $post_uri['path'], $post_uri['options']);
  $variables['post_name'] = check_plain($election_type['post name']);

  $variables['full_name'] = t('@first_name @last_name', array('@first_name' => $candidate->first_name, '@last_name' => $candidate->last_name));

  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Make the field variables available with the appropriate language.
  field_attach_preprocess('election_candidate', $candidate, $variables['content'], $variables);

  $variables['classes_array'][] = drupal_html_class('election-' . $election->type . '-candidate');

  $variables['theme_hook_suggestions'][] = 'election_candidate__' . $candidate->candidate_id;
  $variables['theme_hook_suggestions'][] = 'election__' . $election->type . '__candidate';
  $variables['theme_hook_suggestions'][] = 'election__' . $election->election_id . '__candidate';

}

/**
 * Process variables for election-candidate-details.tpl.php
 *
 * The $variables array contains the following arguments:
 * - $candidate
 * - $election
 * - $page
 *
 * @see election-candidate.tpl.php
 */
function template_preprocess_election_candidate_details(&$variables) {

  $variables['election'] = $variables['elements']['#election'];
  $variables['candidate'] = $variables['elements']['#candidate'];
  $variables['post'] = $variables['elements']['#post'];

  $election = $variables['election'];
  $candidate = $variables['candidate'];
  $post = $variables['post'];
  $election_type = _election_type_get_info($election->type);

  if (empty($post)) {
    // Handle gracefully when the candidate's post is deleted prematurely.
    $post = entity_get_controller('election_post')->create(array(
      'type' => $election_type['post key'],
    ));
  }

  $uri = entity_uri('election_candidate', $candidate, $election);
  $variables['url'] = url($uri['path'], $uri['options']);

  $election_uri = entity_uri('election', $election);
  $variables['election_url'] = url($election_uri['path'], $election_uri['options']);
  $variables['election_link'] = l($election->title, $election_uri['path'], $election_uri['options']);

  $post_uri = entity_uri('election_post', $post);
  $variables['post_url'] = url($post_uri['path'], $post_uri['options']);
  $variables['post_link'] = l($post->title, $post_uri['path'], $post_uri['options']);

  $variables['full_name'] = t('@first_name @last_name', array('@first_name' => $candidate->first_name, '@last_name' => $candidate->last_name));

  $variables['content']['election'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-election'),
    ),
    '#markup' => '<span class="label">' . t('Election:') . '</span>'
               . ' <span class="item">' . $variables['election_link'] . '</span>',
  );

  $variables['content']['post'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-post'),
    ),
    '#markup' => '<span class="label">' . drupal_ucfirst($election_type['post name'] . ':') . '</span>'
               . ' <span class="item">' . $variables['post_link'] . '</span>',
  );

  $variables['content']['full-name'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-full-name'),
    ),
    '#markup' => '<span class="label">' . t('Name:') . '</span>'
               . ' <span class="item">' . $variables['full_name'] . '</span>',
  );

  $variables['username'] = theme('username', array('#account' => $candidate->uid? user_load($candidate->uid) : NULL));
  $variables['phone'] = check_plain($candidate->phone);
  $variables['mail'] = l($candidate->mail, 'mailto:' . $candidate->mail, array('absolute' => TRUE));

  $variables['content']['mail'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-email-address')
    ),
    '#markup' => '<span class="label">' . t('Email address:') . '</span>'
               . ' <span class="item">' . $variables['mail'] . '</span>',
  );

  $variables['content']['phone'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-phone'),
    ),
    '#markup' => '<span class="label">' . t('Phone number:') . '</span>'
               . ' <span class="item">' . $variables['phone'] . '</span>',
  );

  $variables['content']['candidate-username'] = array(
    '#theme' => 'container',
    '#attributes' => array(
      'class' => array('pseudo-field', 'candidate-username'),
    ),
    '#markup' => '<span class="label">' . t('Username:') . '</span>'
               . ' <span class="item">' . $variables['username'] . '</span>',
  );

  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  $variables['classes_array'][] = drupal_html_class('election-' . $election->type . '-candidate', 'election-candidate-details');

  $variables['theme_hook_suggestions'][] = 'election_candidate_details__' . $candidate->candidate_id;
  $variables['theme_hook_suggestions'][] = 'election__' . $election->type . '__candidate_details';
  $variables['theme_hook_suggestions'][] = 'election__' . $election->election_id . '__candidate_details';

}

/**
 * Internal function that determines whether voting/nominating in an election is 'open',
 * based on the status, opening time and closing time.
 *
 * @param int $status
 *   The vstatus/nstatus of the election (see election.install).
 * @param int $open_time
 *   The UNIX timestamp for the election's voting opening time.
 * @param int $close_time
 *   The UNIX timestamp for the election's voting closing time.
 *
 * @return bool
 */
function _election_is_open($status, $open_time, $close_time) {
  if ($status == ELECTION_STATUS_OPEN) {
    return TRUE;
  }
  if ($status == ELECTION_STATUS_CLOSED) {
    return FALSE;
  }
  return (
    $open_time && REQUEST_TIME >= $open_time
    && (!$close_time || REQUEST_TIME < $close_time)
  );
}

/**
 * Internal function to format the voting/nominating status (vstatus/nstatus)
 * field of an election for display.
 *
 * @todo make this themeable
 *
 * @param stdClass $election
 * @param string $status_prefix
 *   The type of status ('v' for voting, 'n' for nominations).
 *
 * @return string
 */
function _election_format_status(stdClass $election, $status_prefix = 'v') {
  // Nominations aren't relevant to referendums.
  // @todo make this extensible
  if (@$election->type == 'referendum' && $status_prefix == 'n') {
    return t('N/A');
  }
  $status = $election->{$status_prefix . 'status'};
  $open_time = @$election->{$status_prefix . 'open_time'};
  $close_time = @$election->{$status_prefix . 'close_time'};
  $open_status = t('<span class="election-status-open">Open</span>');
  $closed_status = t('<span class="election-status-closed">Closed</span>');
  if ($status == ELECTION_STATUS_SCHEDULED) {
    $scheduled_future = t('Scheduled for the future');
    $scheduled_past = t('Scheduled for the past');
    $scheduled_now = t('Scheduled (now open)');
    if (REQUEST_TIME < $open_time) {
      return $scheduled_future;
    }
    elseif (REQUEST_TIME < $close_time) {
      return $scheduled_now;
    }
    else {
      return $scheduled_past;
    }
  }
  $is_open = _election_is_open($status, $open_time, $close_time);
  return $is_open? $open_status : $closed_status;
}

/**
 * Internal function to format the status field of an election post for display.
 * Election posts can either inherit the election's status, or they can be
 * closed. This applies to both voting and nominations.
 *
 * @todo make this themeable
 *
 * @param stdClass $election
 * @param stdClass $post
 * @param string $type
 *   The type of status ('v' for voting, 'n' for nominations).
 *
 * @return string
 */
function _election_post_format_status(stdClass $election, stdClass $post, $status_prefix = 'v') {
  $status = $post->{$status_prefix . 'status'};
  if ($status == ELECTION_POST_STATUS_INHERIT) {
    return t('!status (inherited)', array('!status' => _election_format_status($election, $status_prefix)));
  }
  $is_open = FALSE; // only two options for now are inherited or closed.
  $open_status = t('<span class="election-post-status-open">Open</span>');
  $closed_status = t('<span class="election-post-status-closed">Closed</span>');
  $status_formatted = $is_open? $open_status : $closed_status;
  return t('!status_formatted (overridden)', array('!status_formatted' => $status_formatted));
}

/**
 * Internal function to format the status field of an election candidate for display.
 *
 * @todo make this themeable
 *
 * @param stdClass $candidate
 *
 * @return string
 */
function _election_candidate_format_status(stdClass $candidate) {
  switch ($candidate->cstatus) {
    case ELECTION_CANDIDATE_APPROVED:
      return t('Approved');
      break;
    case ELECTION_CANDIDATE_REJECTED:
      return t('Nomination rejected');
      break;
    case ELECTION_CANDIDATE_PENDING:
    default:
      return t('Pending approval');
      break;
  }
}

/**
 * General function for creating breadcrumbs. Accepts any number of parameters,
 * each corresponding to the breadcrumb link. Output must be sanitized before
 * passing to this function. The string '_POST_' will be replaced by the
 * election's post type name.
 *
 * @param stdClass $election
 * @param string $part
 *
 * @return array
 *   An array of breadcrumb parts that can be provided to drupal_set_breadcrumb().
 */
function _election_build_breadcrumb(stdClass $election = NULL) {
  $args = func_get_args();
  $links = array();
  $links[] = l(
    t('Home'),
    '<front>'
  );
  $links[] = l(
    t('Elections  '),
    'elections'
  );
  if (!is_object($election)) {
    return $links;
  }
  $election_uri_path = election_uri_path($election);
  unset($args[0]);
  $args_count = count($args);
  $links[] = l(
    $election->title, // l() runs check_plain anyway.
    $election_uri_path
  );
  foreach ($args as $key => $arg) {
    $link = $arg;
    switch ($arg) {
      case '_POSTS_':
        $posts_name = _election_get_posts_name($election->type, TRUE);
        $link = l(drupal_ucfirst($posts_name), $election_uri_path . '/posts');
        break;
      case '_CANDIDATES_':
        $link = l(t('Candidates'), $election_uri_path . '/candidates');
        break;
    }
    $links[] = $link;
  }
  return $links;
}

/**
 * Internal function: load election type information by its machine name.
 *
 * @param string $type_mn
 *   The machine name of the type.
 * @return mixed
 *   A stdClass election type object, or FALSE on failure.
 */
function _election_type_get_info($type_mn) {
  $type = array(
    'name' => t('Unknown type'),
    'post key' => 'post',
    'post name' => t('post'),
    'post name plural' => t('posts'),
  );
  $types = election_types();
  if (isset($types[$type_mn])) {
    $type = $types[$type_mn];
  }
  return $type;
}

/**
 * Get the post name (i.e. 'motion' or 'position') for an election type.
 *
 * @param string $type_mn
 * @param bool $plural
 *
 * @return string
 */
function _election_get_posts_name($type_mn, $plural = FALSE) {
  $name = 'post';
  $type = _election_type_get_info($type_mn);
  if (!$type) {
    return $name;
  }
  if (!empty($type['post name'])) {
    $name = $type['post name'];
  }
  if ($plural && !empty($type['post name plural'])) {
    $name = $type['post name plural'];
  }
  return $name;
}

/*
 * Implements hook_file_download_access().
 *
 * Allow private files to be downloaded when they are attached to an election
 * entity via a file field.
 *
 * @param string $field
 * @param string $entity_type
 * @param string $entity
 */
function election_file_download_access($field, $entity_type, $entity) {
  if ($entity_type == 'election') {
    return election_access('view', $entity);
  }
  if ($entity_type == 'election_post' && !empty($entity->election_id)) {
    $election = election_load($entity->election_id);
    return election_access('view', $election);
  }
  if ($entity_type == 'election_candidate') {
    return election_candidate_access('view', $entity);
  }
}

/*
 * Implements hook_views_default_views().
 */
function election_views_default_views() {
  $views_files = array(
    './' . drupal_get_path('module', 'election') . '/views/all_elections.inc'
  );
  $views = array();
  foreach ($views_files as $filename) {
    include_once $filename;
  }
  return $views;
}

/**
 * Implements hook_menu_position_rule_plugins().
 */
function election_menu_position_rule_plugins() {
  return array(
    'election' => array(
      'form_callback' => 'election_menu_position_rule_election_form',
      'condition_callback' => 'election_menu_position_condition_election',
      'file' => 'includes/election.menu-position.inc',
    ),
  );
}
