<?php
/**
 * Implements hook_electorate_info().
 */
function election_electorates_electorate_info() {
  $electorates = array();
  $electorates['gmail'] = array(
    'name' => t('GMail users'),
    'access callback' => 'election_electorates_gmail',
    'description' => t('Users whose registered email addresses end with either "gmail.com" or "googlemail.com".'),
  );
  return $electorates;
}

/**
 * Authorises users whose registered email addresses end with either "gmail.com"
 * or "googlemail.com".
 *
 * @see election_electorates_electorate_info()
 *
 * @param stdClass $user
 *
 * @return bool
 */
function election_electorates_gmail(stdClass $user) {
  return (bool) preg_match('/g(oogle)?mail\.com\s*\b/i', $user->mail);
}