<?php
/**
 * @file
 * Election Statistics primary module file.
 */

/**
 * Implements hook_menu().
 */
function election_statistics_menu() {
  $items = array();

  $items['election/%election/statistics'] = array(
    'title' => 'Statistics',
    'page callback' => 'election_statistics_page',
    'page arguments' => array(1),
    'access callback' => 'election_statistics_access',
    'access arguments' => array('view', 1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function election_statistics_permission() {
  $permissions = array(
    'view election statistics' => array(
      'title' => t('View election statistics'),
      'description' => t('This allows the user to view election statistics, if they already have permission to view the election.'),
    ),
  );
  return $permissions;
}

/**
 * Access callback for viewing an election's statistics.
 */
function election_statistics_access($op, $election, $account = NULL) {
  if (!election_access('view', $election, $account)) {
    return FALSE;
  }
  return user_access('view election statistics');
}

/**
 * Implements hook_theme().
 */
function election_statistics_theme() {
  return array(
    'election_statistics' => array(
      'variables' => array(
        'election' => NULL,
      ),
      'file' => 'election_statistics.theme.inc',
    ),
  );
}
/**
 * Page callback for election/%election/statistics.
 */
function election_statistics_page(stdClass $election) {
  drupal_set_title(t('Statistics: %election', array('%election' => $election->title)), PASS_THROUGH);
  drupal_set_breadcrumb(_election_build_breadcrumb($election));
  return theme('election_statistics', array('election' => $election));
}
