<?php
/**
 * @file
 * 'Example conditions' primary module file.
 */

/**
 * Define the example conditions. Implements hook_election_condition_info().
 */
function election_example_conditions_election_condition_info() {
  $conditions = array();
  $conditions['gmail'] = array(
    'name' => t('Have a Gmail account'),
    'callbacks' => array('election_example_conditions_access_gmail'),
    'description' => t('The user\'s registered email address must end with "gmail.com" or "googlemail.com".'),
  );
  $conditions['hotmail'] = array(
    'name' => t('Have a Hotmail account'),
    'callbacks' => array('election_example_conditions_access_hotmail'),
    'description' => t('The user\'s registered email address must end with "hotmail.com" or "hotmail.co.uk".'),
  );
  return $conditions;
}

/**
 * Have a Gmail account condition.
 *
 * Authorise users whose registered email addresses end with either "gmail.com"
 * or "googlemail.com".
 */
function election_example_conditions_access_gmail(stdClass $account) {
  if ($account->uid == 0) {
    return FALSE;
  }
  return (bool) preg_match('/g(oogle)?mail\.com\s*\b/i', $account->mail);
}

/**
 * Have a Hotmail account condition.
 *
 * Authorise users whose registered email addresses end with either
 * "hotmail.com" or "hotmail.co.uk".
 */
function election_example_conditions_access_hotmail(stdClass $account) {
  if ($account->uid == 0) {
    return FALSE;
  }
  return (bool) preg_match('/hotmail\.com\s*\b/i', $account->mail);
}
