<?php
/**
 * @file
 * 'Example conditions' primary module file.
 */

/**
 * Have a Gmail account condition.
 *
 * Authorise users whose registered email addresses end with either "gmail.com"
 * or "googlemail.com".
 */
function election_example_conditions_access_gmail(stdClass $post, stdClass $account) {
  if ($account->uid == 0) {
    return FALSE;
  }
  return (bool) preg_match('/g(oogle)?mail\.com\s*\b/i', $account->mail);
}

/**
 * Have a Hotmail account condition.
 *
 * Authorise users whose registered email addresses end with either
 * "hotmail.com" or "hotmail.co.uk".
 */
function election_example_conditions_access_hotmail(stdClass $post, stdClass $account) {
  if ($account->uid == 0) {
    return FALSE;
  }
  return (bool) preg_match('/hotmail\.com\s*\b/i', $account->mail);
}
